image:
  file: .gitpod.dockerfile
ports:
  - port: 8000
    onOpen: ignore
tasks:
  - init: pip install -r requirements.txt
    command: mysql -e ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';
    # command: uvicorn main:app --reload

vscode:
  extensions:
    - ms-python.python
